# Generated by Django 2.2.10 on 2020-09-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='logo',
        ),
    ]
